install bullet-cmd
install direnv
install ghostscript
install imagemagick
install jq
install opam
install parallel
install tig
install zsh
install nkf
install pandoc
install watch
install logstash
install gmp
install gnupg
install elasticsearch
install wget
install tmux
install peco
install pstree
install go
install htop-osx
install coreutils
install speedtest_cli
install nkf
install watch
install objective-caml
