(add-hook 'c++-mode-hook
      '(lambda ()
        (setq tab-width 4)
        (setq c++-argdecl-indent 0)
        (setq c++-continued-statement-offset 4)
        (setq c++-indent-level 4)
        (setq c++-label-offset -2)
        (setq c++-tab-always-indent nil)
        (setq case-fold-search nil)
	(define-key c++-mode-map "{" 'insert-braces)
	(define-key c++-mode-map "(" 'insert-parens)
	(define-key c++-mode-map "\"" 'insert-double-quotation)
	(define-key c++-mode-map "[" 'insert-brackets)
	(define-key c++-mode-map "}" 'insert-braces-region)
	(define-key c++-mode-map ")" 'insert-parens-region)
	(define-key c++-mode-map "]" 'insert-brackets-region)
	(define-key c++-mode-map "\"" 'insert-double-quotation-region)))

(setq gdb-many-windows t)
(setq gdb-use-separate-io-buffer nil)
